/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 06-nov.-2019 11:32:15 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS Area CASCADE
;

DROP TABLE IF EXISTS Ciclo_propedeutico CASCADE
;

DROP TABLE IF EXISTS Institucion_educativa CASCADE
;

DROP TABLE IF EXISTS Otras_herramientas CASCADE
;

DROP TABLE IF EXISTS Persona CASCADE
;

DROP TABLE IF EXISTS ResultadoCompetenciasTIC CASCADE
;

DROP TABLE IF EXISTS ResultadoHerramientas CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE Area
(
	`k_id` DECIMAL(10,0) NOT NULL,
	`n_nombre` VARCHAR(50) NOT NULL,
	`n_detalles` VARCHAR(80) NULL,
	CONSTRAINT `PK_Area` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Ciclo_propedeutico
(
	`k_id` DECIMAL(1,0) NOT NULL COMMENT 'Identificador unico que cada uno de los 3 ciclos propedeuticos.',
	`n_nombre` VARCHAR(30) NOT NULL,
	`n_descripcion` VARCHAR(50) NULL,
	CONSTRAINT `PK_Ciclo_propedeutico` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Institucion_educativa
(
	`k_id` DECIMAL(8,0) NOT NULL,
	`n_nombre` VARCHAR(50) NOT NULL,
	`n_detalles` VARCHAR(80) NULL,
	CONSTRAINT `PK_Institucion_educativa` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Otras_herramientas
(
	`k_id` DECIMAL(8,0) NOT NULL,
	`v_valor` VARCHAR(15) NOT NULL,
	`v_tipo` VARCHAR(15) NOT NULL,
	`k_cedula_resultados` VARCHAR(11) NULL,
	CONSTRAINT `PK_Otras_herramientas` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Persona
(
	`k_cedula` VARCHAR(11) NOT NULL,
	`n_nombre` VARCHAR(50) NULL,
	`o_genero` VARCHAR(1) NULL,
	`n_email` VARCHAR(50) NULL,
	`fk_id_institucion` DECIMAL(8,0) NULL,
	`k_id_area` DECIMAL(10,0) NULL,
	`k_id_ciclo` DECIMAL(1,0) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE ResultadoCompetenciasTIC
(
	`v_competenciaTecnologica` DECIMAL(1,0) NOT NULL,
	`v_competenciaPedagogica` DECIMAL(1,0) NOT NULL,
	`v_competenciaComunicativa` DECIMAL(1,0) NOT NULL,
	`v_competenciaGestion` DECIMAL(1,0) NOT NULL,
	`k_cedula` VARCHAR(11) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE ResultadoHerramientas
(
	`v_trabajoColaborativo` VARCHAR(50) NOT NULL,
	`v_OVA` VARCHAR(50) NOT NULL,
	`v_audio` VARCHAR(50) NOT NULL,
	`v_texto_imagenes` VARCHAR(50) NOT NULL,
	`v_presentacion` VARCHAR(50) NOT NULL,
	`v_videoConferencia` VARCHAR(50) NOT NULL,
	`v_comunidades` VARCHAR(50) NOT NULL,
	`v_bibliografico` VARCHAR(50) NOT NULL,
	`v_mapas` VARCHAR(50) NOT NULL,
	`v_lineas` VARCHAR(50) NOT NULL,
	`v_actividades` VARCHAR(50) NOT NULL,
	`v_LMS` VARCHAR(50) NOT NULL,
	`v_comunicacion_gestion` VARCHAR(50) NOT NULL,
	`v_estadistica` VARCHAR(50) NOT NULL,
	`k_cedula` VARCHAR(11) NOT NULL,
	CONSTRAINT `PK_ResultadoHerramientas` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE Usuario
(
	`k_id` DECIMAL(8,0) NOT NULL,
	`n_usuario` VARCHAR(30) NOT NULL,
	`n_clave` VARCHAR(100) NOT NULL,
	`k_cedula_persona` VARCHAR(11) NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`k_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Otras_herramientas 
 ADD INDEX `IXFK_Otras_herramientas_ResultadoHerramientas` (`k_cedula_resultados` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Area` (`k_id_area` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Ciclo_propedeutico` (`k_id_ciclo` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Institucion_educativa` (`fk_id_institucion` ASC)
;

ALTER TABLE ResultadoCompetenciasTIC 
 ADD INDEX `IXFK_ResultadoCompetenciasTIC_Persona` (`k_cedula` ASC)
;

ALTER TABLE ResultadoHerramientas 
 ADD INDEX `IXFK_ResultadoHerramientas_Persona` (`k_cedula` ASC)
;

ALTER TABLE Usuario 
 ADD INDEX `IXFK_Usuario_Persona` (`k_cedula_persona` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Otras_herramientas 
 ADD CONSTRAINT `FK_Otras_herramientas_ResultadoHerramientas`
	FOREIGN KEY (`k_cedula_resultados`) REFERENCES ResultadoHerramientas (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Area`
	FOREIGN KEY (`k_id_area`) REFERENCES Area (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Ciclo_propedeutico`
	FOREIGN KEY (`k_id_ciclo`) REFERENCES Ciclo_propedeutico (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Institucion_educativa`
	FOREIGN KEY (`fk_id_institucion`) REFERENCES Institucion_educativa (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE ResultadoCompetenciasTIC 
 ADD CONSTRAINT `FK_ResultadoCompetenciasTIC_Persona`
	FOREIGN KEY (`k_cedula`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE ResultadoHerramientas 
 ADD CONSTRAINT `FK_ResultadoHerramientas_Persona`
	FOREIGN KEY (`k_cedula`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Usuario 
 ADD CONSTRAINT `FK_Usuario_Persona`
	FOREIGN KEY (`k_cedula_persona`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;

/*INSERT INTO institucion_educativa (k_id, n_nombre, n_detalles) VALUES (0, 'Universidad Distrital', 'Facultad de Ingeniería')
/*INSERT INTO institucion_educativa (k_id, n_nombre, n_detalles) VALUES (1, 'Universidad Nacional', 'Facultad de Medio Ambiente')
/*INSERT INTO ciclo_propedeutico (k_id, n_nombre, n_descripcion) VALUES (0, 'profesional universitario', 'Mejor que el SEBA')
/*INSERT INTO area (k_id, n_nombre, n_detalles) VALUES (0, 'Matematicas', 'Abstractisimo')